name: Make build
on: [push, workflow_dispatch]
jobs: 
    get-code: 
        runs-on: ubuntu-latest
        steps: 
            - name: Get code
              uses: actions/checkout@v4
            - name: Install deps
              run: npm ci
            - name: Build app
              run: npm run build
    upload-build:
        needs: get-code
        runs-on: ubuntu-latest
        steps:
            - name: Upload build
              uses: actions/upload-artifact@v4