name: First workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo"hello there!"
      - name: Print goodbye
        run: echo"Goodbye"
